[project]
name = "django-faststream"
version = "0.1.0"
description = "Minimal Django project with FastStream and Kafka"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "django>=5.0",
  "faststream[kafka]>=0.5",
  "django-asgi-lifespan",
  "uvicorn[standard]",
]
